:toc: macro

= RFC 1: Keep Network Interface

:icons: font
:numbered:
toc::[]


== Proposal

This document specifies how applications integrate with Keep Network.

=== Terminology

a keep:: A keep is a smart contract.

sMPC cluster:: A keep can have off-chain clients executing work for a keep. All 
               the off-chain clients serving keeps form together sMPC cluster. 
               sMPC cluster observes state of keeps and reacts appropriately. 
               A keep does not directly talk to the cluster.

Keep Network:: Keep Network consists of all keeps and sMPC cluster.

KEEP:: KEEP is ERC20 token staked by Keep Network operators.

Keep Core:: Keep Core consist of a set of on-chain contracts and off-chain  
            client providing the functionality of random beacon
            and KEEP token along with all stake management interfaces.

Application:: Application is an external smart contract or a set of smart  
              contracts utilizing functionalities offered by Keep Network.

tECDSA:: Threshold Elliptic Curve Digital Signature Algorithm. 

Bond:: Bond is a security instrument preventing network operators to collude 
       and act against agreed rules, for example to censor withdrawals or 
       abscond with funds.


=== Goal
The goal of this proposal is to specify the interface between  application and 
keeps on a top of which the application is built. This proposal specifies 
mechanism of creating and registering keeps. This proposal introduces two types
of keeps: tECDSA keep and Bonded tECDSA keep.

==== sMPC cluster requirements

Each off-chain client of sMPC cluster should be a separate process. Keep Core 
client should be a separate client than Keep tECDSA client:
```
./keep-core
./keep-tecdsa 
```

Each staker is required to run Keep Core client. Running Keep tECDSA client is 
optional.

==== Bonding requirement

Some applications requires a bond to be provided by signers. Stakers who want to 
participate in signing need to opt-in and provide the required bond. A bond can 
be provided in ETH or ERC-20 token specific to the application.

=== Implementation

==== ECDSA keep registry

ECDSA keep registry is an on-chain factory of ECDSA keeps. The factory creates 
and destroys keeps and is responsible for maintaining the list of all active 
keeps. sMPC cluster clients working with ECDSA keeps observe ECDSA keep registry 
for all new ECDSA keeps created. Registry is responsible for group selection 
using the random beacon.

===== Pseudocode

```
contract ECDSAKeepRegistry {
    address[] internal _keeps;

    function openNewKeep(
        uint256 threshold, 
        uint256 groupSize, 
        address owner
    ) returns (address) {
        address keep = new ECDSAKeep(
            selectGroup(threshold, groupSize), 
            owner
        );

        _keeps.push(keep);
        return keep;
    }

    // (...)
}

contract ECDSAKeep {
    // (...)

    function sign() { 
        require(msg.sender == _owner, "Only keep owner can ask to sign");
        // (...)
    }
}
```

==== Bonded ECDSA keep registry

Bonded ECDSA keep registry is an on-chain factory of Bonded ECDSA keeps. The 
factory creates and destroys keeps and is responsible for maintaining the list 
of all active keeps. Bonded ECDSA keep has extra bonding logic over a vanilla 
ECDSA keep. Registry is responsible for group selection using the random beacon.

===== Pseudocode

```
contract BondedTECDSAKeepRegistry is ECDSAKeepRegistry {
    function openNewKeep(
        uint256 threshold, 
        uint256 groupSize,
        Bond bond, 
        address owner
    ) returns (address) {
        address keep = new ECDSAKeep(
            selectGroup(threshold, groupSize, bond), 
            owner
        );

        _keeps.push(keep);
        return keep;
    }

    // (...)
}

contract BondedECDSAKeep is ECDSAKeep {
    // (...)
}
```


==== Keep registry

Keep registry is an interface for application to interact with Keep Network. Keep 
registry specifies what are the sanctioned types of keep factories and is an 
upgrade mechanism for the entire system. Application interacts with Keep registry to 
open a keep. The registry returns a brand new instance of the requested type of 
a keep. All sanctioned keep factories need to be registered in Keep registry.

===== Pseudocode

```
contract Application {
    address internal _keepRegistry;

    function openDeposit() {
        address keep = KeepRegistry(_keepRegistry).openBondedECDSAKeep(
            threshold, 
            groupSize, 
            bond
        );

        // (...)
    }
}

contract KeepRegistry {
    address internal _bondedTECDSAKeepRegistry;    

    function openBondedECDSAKeep(
        uint256 threshold, 
        uint256 groupSize, 
        Bond bond
    ) returns (address) {
        keep = BondedTECDSAKeepRegistry(_bondedTECDSAKeepRegistry).openNewKeep(
            threshold,
            groupSize,
            bond
            msg.sender,
        );

        return address(keep);
    }

    // (...)
}
```

[bibliography]
== Related Links

- Discussions on writing this document:
https://github.com/keep-network/tbtc/issues/109
