:toc: macro

= RFC 1: Keep Network Interface

:icons: font
:numbered:
toc::[]


== Proposal

This document specifies how tBTC application integrates with Keep Network.

=== Terminology

a keep:: A keep is a smart contract.

sMPC cluster:: A keep can have off-chain clients executing work for a keep. All 
               the off-chain clients serving keeps form together sMPC cluster. 
               sMPC cluster observes state of keeps and reacts appropriately. 
               A keep does not directly talk to the cluster.

Keep Network:: Keep Network consists of all keeps and sMPC cluster.

KEEP:: KEEP is ERC20 token staked by Keep Network operators.

Keep Core:: Keep Core consist of a set of on-chain contracts and off-chain  
            client providing the functionality of Random Beacon
            and KEEP token along with all stake management interfaces.

tBTC:: tBTC is the first application written on a top of Keep Network. It 
       provides a decentralized, redeemable, BTC-based ERC-20 token along with 
       all mechanisms needed to satisfy all crypto-economy model requirements. 

tECDSA:: Threshold Elliptic Curve Digital Signature Algorithm. 

Bond:: Bond is a security instrument preventing network operators to collude 
       to censor withdrawals or abscond with funds.


=== Goal
The goal of this proposal is to specify the interface between the tBTC 
application and keeps on a top of which the application is built. This proposal specifies mechanism of creating and registering keeps.

==== sMPC cluster requirements

Each off-chain client of sMPC cluster should be a separate process. Keep Core 
client should be a separate client than Keep tECDSA client:
```
./keep-core
./keep-tecdsa 
```

Each staker is required to run Keep Core client. Running Keep tECDSA client is optional.

==== Bonding requirement

tBTC application requires a bond to be provided by signers. Stakers who want to participate in signing need to opt-in and provide the required bond. A bond can 
be provided in ETH or tBTC.