:toc: macro

= Handling Failure

ifndef::tbtc[toc::[]]

== Deposits

=== Overpayments

== Signers

=== Undercollateralization

:first-threshold: 140%
:second-threshold: 125%


Signer collateral is fixed on _Depoist_ creation. Should the price of the host
chain asset change significantly relative to BTC, the signers may become
undercollateralized. Future versions of the system may allow signers to
recollateralize as a group. However, coordinating an entire signing group is a
complex task. Undercollaterization threatens the health of the _Deposit_, so
the system responds to it at 2 thresholds. First, when collateralization
falls to {first-threshold} we begin the pre-liquidation timer. Then should it
fall further to {second-threshold} collateralization we being the liquidation
process immediately.

=== Pre-liquidation: a courtesy call
[[preliq]]

:preliquidation-period: 6 hours

At the first threshold, a _Deposit_ enters pre-liquidation. Pre-liquidation
indicates that the signers should be close the _Deposit__ or face forced
liquidation. If the _Deposit_ is not closed within {preliquidation-period}, or
if the _Deposit_ collateral falls below {second-threshold} collateralization,
liquidation will follow. This gives each signer an incentive to close the
position before it becomes severely undercollateralized, as all signers risk
losing funds in the liquidation process.

In future versions of the system, more complex pre-liquidation mechanisms could
be introduced. For the initial version it seems prudent to choose a simple
mechanism with large penalties for ongoing undercollateralization.


=== Liquidation

Forced liquidation should be rare, as rational signers will redeem _Deposits_
before liquidation becomes necessary. However, the possibility of extreme
punishment via liquidation is necessary to prevent dishonest behavior from
signers. Liquidation may occur because because signers didn't produce a valid
signature  in response a redemption request, because the value of the signing
bond dropped below the collateralization threshold, or because the signers
produced an unauthorized signature.

The primary goal of the liquidation process is to bring the TBTC supply in line
with the BTC custodied by _Deposits_. The most valuable asset held by the
system is the signers' bonds. Therefore, the liquidation process seizes the
signers bonds and attempts to use the bonded value to purchase and burn TBTC.

// TODO: cite uniswap
First, the contract attempts to use on-chain liquidity sources, such as
Uniswap. If the bond is sufficient to cover the outstanding TBTC value on these
markets, it is immediately exchanged for TBTC.

Second, the contract starts a falling-price auction. It offers 75% of the signer
bond for sale for the outstanding TBTC amount. The amount of bond on sale
increases over time until someone chooses to purchase it, or the auction
reaches 100% of the bond. The auction will remain open until a buyer is found.

TBTC received during this process is burned to maintain the supply peg. If any
bond value is left after liquidation, a small fee is distributed to the account
which trigger liquidation. After that, any remaining value is either
distributed to the signers (in case of liquidation due to
undercollateralization) or burned (in case of liquidation due to fraud).

What the unresponsive signers do with the BTC outside the tBTC system design is
for them to decide-- it might be split up, stolen by a signing majority, or
lost permanently.

=== Aborts / Liveness

The system requires that critical actions like funding and redemption occur
within a fixed time after request. Failure to do so is treated as an "abort."
Where <<Fraud, fraud>> indicates proof positive of forbidden behavior, an
abort typically represents a liveness failure from some participant. As such,
while aborts are still punished, and may still result in liquidation, they are
not punished as severely as fraud. For example, should the signers fail to
produce a redemption signature in a timely manner, their bonds are liquidated
to protect the supply peg, but any remainder is returned to them.

=== Fraud

The system recognizes two redundant fraud proofs: ECDSA, in which the signing
group produces a signature on a message which was not explicitly requested,
and SPV, in which the UTXO custodied by the signing group moves for an unknown
reason. Intuitively, the UTXO should not be able to move without ECDSA fraud,
however, the system accepts either proof (and may require both proofs in
certain cases). Each proof its own limitations and security parameters. When
fraud is detected, the system penalizes the signers by seizing their bonds and
starting the <<Liquidation>> process.

==== ECDSA Fraud Proofs

The signers collectively control an ECDSA keypair. By cooperating, they can
produce signatures under the public key. Signers are charged with producing
certain signatures (e.g. on a redemption transaction during the redemption
process). Any valid signature under the signers' public key, but not
specifically requested by the system is considered fraud.

An ECDSA fraud proof is simply a signature under the signers' public key, the
signed message digest, and the preimage of that digest. From there we perform
regular ECDSA verification. If the preimage matches the digest and the
signature on the digest is valid but the digest was not explicitly requested by
the system, then we can be sure that the signer set is no longer reliable. It
is worth noting here, that verification of the preimage-digest relationship may
not be skipped. Given any public key, it is possible to construct a signature
under that public key and select a digest that matches it. Which is to say,
anyone can produce an apparently valid signature on any unknown message.
Only direct verification of the preimage's existence (via checking its
relationship to the signed digest) prevents this attack as the attacker would
have to invert the hash function to forge this relationship.

Notionally, the system can verify any signature the signers produce. However,
the capabilities of the host chain set practical limitations. For instance, on
Ethereum, only certain digest functions are available, so we cannot verify
signatures on digests produced by unsupported hash functions. As a practical
example, this precludes verification of Decred signatures, which use blake256.
Signers in an Ethereum-hosted system can produce signatures on Decred
transactions with no possibility of punishment.

All host chain impose costs on argument size, Therefore cost of verification
scales with the length of the preimage. This means that it may not be
economically feasible to verify signatures on very long pre-images, or that
attempting to do so will exceed resource-use limitations (e.g. Ethereum's block
gas limit). Fortunately, Bitcoin's signature hash algorithm uses double-sha256.
This means that the preimage to the signed digest is always 32 bytes. As such,
verification costs never scale with transaction size, and even very large
transactions do not evade ECDSA fraud verification.

==== SPV Fraud Proofs

// TODO: link SPV description

The signers custody a single Bitcoin UTXO. If that UTXO moves, except at the
direction of the system then the signers have failed to perform their duties.
SPV Proofs of Bitcoin inclusion (as documented here) suffice to prove signer
fault. If the coins move, and its movement was not specifically requested by
the system, then the signers have failed in their custodial duties. Compared to
ECDSA Fraud proofs, SPV Fraud Proofs are more expensive to verify and have a
weaker security model. The system expects SPV Fraud Proofs only rarely, and
subjects them to much higher work requirements than SPV funding and redemption
proofs.
