== Glossary

Stake:: An amount of KEEP that is bonded in order to participate in the
  threshold relay and, optionally, the Keep network. Part or all of this can be
  removed from escrow as penalties for misbehavior, while part or all of it can
  be refunded if and when a participant chooses to withdraw in orderly fashion
  from the network and relay.

Staker:: A staking client that has a stake, but may not yet be in a signing
  group.

Minimum Stake Amount:: The minimum stake amount that will make a staking client
  a staker, as required by the staking smart contract.

Stake Amount:: Total KEEP deposited for a single stake.

Signing Member:: One member of one complete signing group in the threshold
  relay.

Signing Group:: One complete signing group in the threshold relay.

Lead Signing Group:: The signing group that will produce the next relay entry
  candidate (due to being the result of $E_i mod N$ with $E_i$ being the
  current entry and $N$ being the number of groups). If this group fails to
  respond to the request in time, the lead responsibility may shift to another
  group.

Relay Entry Candidate:: A random number generated by the threshold relay that
  has not yet been finalized on the blockchain; may be invalid.

Relay Entry:: A relay entry candidate that has been finalized on the blockchain;
  may be invalid.

Keep Client:: The entire application running on a user's system, which contains
  multiple subclients for the various pieces of the Keep system.

Staking Client:: The part of the Keep Client that stakes and participates in the
  threshold relay.

Verifying Client:: Verifies entries on-chain and reports invalid entries.
  Optional, does not require a stake. Reward for identifying an invalid random
  number on the chain.

Provider Client:: The Keep Provider piece of the application, which can in turn
  have workers for various Keep types.

Keep Type:: The functionality that the given Keep relies on for providing
  security. e.g. an SHM (Secure Hardware Module) Keep, SMPC (Secure Multi-Party
  Computation) Keep, Proxy Reencryption Keep, etc.

Provider Worker:: One worker that runs the code to allow a provider client to
  participate in a given Keep Type.

Keep Provider:: One economic entity in the Keep network; has a stake, must
  participate in a signing group as a single member.

Keep:: Up to 1MB of encrypted storage across one or more Keep Providers.

KEEP:: Token used to stake. Can be represented as a K with a vertical bar
  through it.

Keep Owner, Delegate, Requester are described in the whitepaper.
