:toc: macro
:toclevels: 4
:tbtc:

= TBTC: A Decentralized Redeemable BTC-backed ERC-20 Token

toc::[]

[abstract]
.Abstract
--
--

== Overview

== Prior Work

* Liquid - centralized, fiat, provable, redeemable
* WBTC - centralized, fiat, provable, redeemable
* Maker - decentralized, synthetic (irredeemable)

downsides of a "fiat" BTC peg
* note this includes all current sidechain implementations AFAIK

downsides of a synthetic BTC
* need more diverse / resilient collateral, and that's difficult to find on-chain
* upsides - there might be some value to having an asset pegged to BTC that doesn't

== Desired Properties

The goal of TBTC is the creation an ERC-20 token that maintains the most
important property of Bitcoin- its status as "hard money".

To maintain the "hard money" status of its backing BTC deposits, TBTC must
remain

.Bulleted
* Censorship and seizure resistant, across friendly and unfriendly
jurisdictions
* Inflation-resistant. TBTC may only be minted after proof is provided of a
backing BTC deposit.
* Leverage-resistant. The existence of TBTC shouldn't let a Bitcoin holder
* Without middlemen, in the same sense as Bitcoin. The only rent extraction
should be from the minimal participation of signers required to secure the
network, similar to miners on the Bitcoin network.

Finally, TBTC must be *redeemable*. The ability to trade scrip for its backing
deposit freely is what distinguishes a backed currency from fiat money.

== Developing Intuition: A simple single-signer protocol

=== The downsides of a single signer

== System Architecture: Designing a robust multi-wallet multi-signer protocol

Include high-level components

expected components outside the scope of this doc
* random beacon
* well-distributed work token

components in this protocol
* deposits
** mechanic
*** DKG
*** payment requests
*** fixed lots
*** BTC work proof
** signer bonding
** custodial fee
* signing
** single vs multisig vs threshold sig
* handling failure
** slashing
** aborts
** liveness
** fraud
* redemption
