[#signer-fees]
= Signer Fees

Signers put their own <<Bonding,funds at risk>> to assure depositors there will
be no foul play. The bonds they put down are capital that could otherwise be
productive, and need to earn a return relative to the risk to remain competitive
with other opportunities.

== Paying for security

There are a number of pricing models that could cover the opportunity cost of
signers' bonds.

An adjacent space offers a pricing model that works as a floor.

Today's centralized cryptocurrency custodians charge 50 to 75 basis points
(between 0.5-0.75%) on _assets under custody (AUC)_ per year. For each year
that a centralized custodian protects a bitcoin deposit, that's as much as
0.75% lost to the costs of custody.

A decentralized model should eventually allow a lower effective fee on custody
by introducing more competition to the space. There's a caveat, however -- a
decentralized approach to custodianship makes legal recourse more difficult,
requiring additional bonded collateral to ensure recompense in case of failure.

Applying this pricing model to tBTC's bonding, it's clear that a Signer would
need to make a similar return at a minimum on the total capital it's protecting.

== Fee parameterization

=== Terminology

- `Deposit`: A non-fungible smart contract construct to which a signing group is
  assigned. It coordinates the creation and redemption of `LotSize * 1 TBTC`.
- `LotSize`: The exact value of a `Deposit` denominated in `BTC`.
- `OvercollateralizationFactor`: The additional amount which must be deposited
   as collateral by the Signer.
- `BondValue`: The amount a `Signer` must lock in a smart contract as
  collateral to mint `TBTC`. Initially this will be denominated in `ETH`.
  `Deposit = OverCollateralizationFactor * LotSize * (ETHBTC conversion rate)`.
  In the future, `TBTC` may be used to collateralize a deposit. As a result,
  assuming a 1:1 ratio between `BTC` and `TBTC`, the price conversion can be
  skipped.
- `N`: The number of Signers authorized to sign on a `Deposit`'s withdrawal
  request.
- `M`: The minimum number of Signers required to sign the authorization of a
  `Deposit`'s withdrawal request.

=== Description

:initial-signers: 15

It is assumed that each `Signer` contributes equally to the collateralization of
a `Deposit`.

The capital cost per `Signer` is `BondValue / N`. Using `LotSize = 1
BTC` and `OverCollateralizationFactor = 150%`, that is `1.5 BTC / N`.

An initial parameterization of the system might use `{initial-signers}` Signers
per lot. In addition, due to the lack of attributability in the
link:../signing/index.adoc[aggregate signature mechanism] used, we pick `M = N`.
This requires a `0.1` BTC value in capital cost for **each** Signer per
`1.0 TBTC` minted.

Taking into account the fees from centralized custodians (`0.0025-0.0075 BTC`),
and considering signers are also risking additional bonds, in an initial
parameterization we choose to reward signers with `0.009375 TBTC` per `1.0 BTC`
deposited. As each deposit has a fixed term of 6 months, that implies a total
signing revenue of `1.875%` of the market cap of `TBTC` each year.
