:toc: macro

[[spv]]
= Introduction aux SPV ("Simplified Payment Verification" ou Simples Vérifications de Paiement)

ifndef::tbtc[]
toc::[]

endif::tbtc[]

== Vue d'ensemble

Bien qu'une explication complète des preuves SPV soit hors du cadre de ce document, il est important de comprendre leurs propriétés comme de nombreux processus critiques pour le système reposent sur une hypothèse de sécurité des preuves SPV. Les preuves SPV sont utilisées lors du <<docs/deposit.adoc#funding,financement de dépôt>>,
<<docs/redemption.adoc#redemption,le retrait>>, and
<<docs/failure.adoc#fraud,la preuve de fraude>> pour informer la blockchain hôte de l'état de l'autre blockchain. Dans la pratique, il n'y a pas d'autre moyen pour que la blockchain hôte soit au courant de l'état ou de l'histoire de l'autre blockchain.

=== Objectivité dans la preuve de travail

Les preuves SPV utilisées dans se systèmes reposent sur une propriété de la Preuve de Travail appelée "objectivité". En termes simples, la preuve de travaille ne peut être contrefaite et aucune information externe n'est nécessaire pour vérifier sa validité. Sans conaître l'histoire de la blockchain, on peut examiner un en-tête de bloc Bitcoin et déterminer (de manière probabiliste) combien de hachages ont été nécessaires pour le générer. Le nombre de hash utilisés pour générer un en-tête représente un coût infalsifiable inhérent à cet en-tête, indépendemment de son contexte ou de son histoire.

Ceci est différent de la Preuve d'Enjeu où le coût de génération d'un en-tête dépend de l'histoire complète de la blockchain. On ne peut pas savoir si les signatures des "stakers" réprésente l'ensemble des validateurs actuels sans l'histoire complète de la blockchain. En d'autres termes, la Preuve de Travail seule a un sens tandis que la Preuve d'Enjeu nécessite un contexte. Bien que l'inspection SPV des systèmes à Preuve d'Enjeu soit possible, le modèle de sécurité est complètement différent. Par ailleurs, l'implémentation est bien plus coûteuse que l'inspection SPV de systèmes objectifs. Cette section ne s'intéresse donc qu'aux vérifications de Preuve de Travail. D'autres versions du système utilisant des inspections SPV de systèmes à Preuve d'Enjeu sont laissées à des travaus futurs.

=== Modèle de sécurité

Dans le consensus de Nakamoto, chaque noeuf suit la chaîne la plus lourde. "Lourde" fait référence à la Preuve de Travail. La chaîne ayant le plus de travail accumulé est désignée comme la plus lourde. Conceptuellement, les noeuds se mettent d'accord pour évaluer les nouvelles informations reçues sur la base d'un ensemble de règles et pour rejeter tout ce qui ne suivrait pas ces règles. Dans la pratique, ces règles définissent les blocks blocs constitués d'en-tête et les transaction, décrivent le format des transactions, et fournissent des règles programmables comme Script et EVM. Les noeufs suivant le protocole prendront toujours les mêmes décisions de validité et choisiront toujours la chaîne la plus lourde ne contenat que des blocs et transactions valides. Les noeuds honnêtes atteignent donc toujours le même état, c'est à dire qu'un consensus est toujours atteint.

Le modèle de sécurité SPV est strictement plus faible que le modèle de consensus Nakamoto mais suffisant pour remplir notre objectif. Le modèle SPV vérifie le travail dans les en-têtes et ne s'assure que d'un sous-ensemble des règles de validité. Les vérificateurs SPV suppose au fond que les mineurs ne vont pas utilisé leurs ressources pour produire une preuve de travail faisant suite à des blocs ou transactions invalides. Ils vérifient la validité d'un ensemble d'en-têtes, y compris en vérifiant le travail dans ces en-têtes, mais ne vérifient pas chaque transaction. Les vérificateurs SPV vérifient uniquement les transactions qui les intéressent. Dans le contexte de tBTC, nous ne sommes intéressés que par des UTXOs précis de la blockchain Bitcoin, donc on ne valide que les transactions et en-têtes liées à ces UTXO plutôt que l'ensemble des transactions. 

Lorsque les hypothèses échouent et que du travail a été effectué pour des transactions invalides, le modèle de sécurité peut aussi échouer. On appelle ces instances des "fausses" preuves et "faux" en-têtes car il s'agit de transactions ou en-têtes sémantiquement invalides pour le système Bitcoin. On pense que ces fausses preuves sont très rares. Cette idée est encrée dans l'économie des systèmes Proof of Work. Si un mineur décide de dédier des ressources à la production de travail pour des transactions invalides, il doit renoncer aux récompenses de mineur tout en ayant dépensé de l'argent dans son matériel et en électricité. Il abandonne les récompenses car les transactions invalides ne pourront jamais être incluses à la blockchain Bitcoin car elles seront rejetées par tous les noeuds entiers de validation. La production de fausses preuves a donc un coût inhérent important. Nous pensons que le système est économiquement sûr tant que le coût de production des fauses preuve est élevé et que le montant pouvant être gagné par la production de fausses preuves est plusieurs ordres de grandeurs plus faible que le coût. 

La sécurité des systèmes SPV bénéficie également d'une hypothèse provenant du modèle de consensus Nakamoto : aucun attaquant ne possède plus de 50% du taux de hachage. En supposant cela vrai, aucun attaquant ne peut générer de preuve de travail Bitcoin plus vite que la blockchain principale. Cela implique que des en-têtes honnêtes sont générés (dans les limites de la distribution de Poisson) avant quelconque en-tête malhonnête. On peut étendre ce modèle en disant que si aucun attaquant n'a plus qu'une fraction
`n`du hashrate actuel sur le réseau Bitcoin (où `n >= 2`), alors les en-têtes honnêtes sont générés `n^-1^ - 1` fois plus vite. Par exemple, un attaquant contrôlant 25% (1/4) du hashrate pourrait générer un en-tête en moyenne toutes les 40 minutes. La chaîne principale, ralentie par la perte de ces 25%, génèrerait un en-tête toutes les 13 1/3 minutes -- trois fois plus vite. Pour tirer parti de cela, la preuve doit s'engager sur des informations récentes qui étaient inconnues de l'attaquant, par exemple un en-tête de bloc passé, ou une nouvelle empreinte de clé publique. Cela fournit une borne inférieur sur le moment auquel l'attaquant commence à générer une fausse preuve.

=== Relais 

Un relais est le système SPV le plus simple conceptuellement. Dans un système de relais, chaque en-tête de preuve de travail est soumis à et vérifié par la blockchain hôte. Les contrats de la blockchain hôte gardent en mémoire le meilleur en-tête connu et tous les en-têtes vus. Une preuve SPV dans un système de relais démontre qu'une transaction est confirmée par le meilleur en-tête vu et est suffisament confirmée de telle sorte que son annulation soit peu probable. Chaque en-tête additionnel dans un relai et dans le consensus qu'il suit sécurise les anciens headers. On devient donc plus sûrs des évènements plus anciens au cours du temps.

=== SPV sans état

Si les relais déclinent la vérification de la validité, les systèmes SPV sans état déclinent tous deux la vérification de la validité et ne parviennent pas à suivre la chaîne la plus lourde. En fait, un SPV sans état ne suit rien du tout. Une preuve SPV sans état repose entièrement sur le travail objectif accumulé dans une tranche d'en-têtes spécifique. Un SPV sans état se compose d'une ou plusieurs transactions, de preuves de Merkle d'inclusion de ces transactions, et d'un ensemble d'en-têtes consécutifs correspondant à ces transactions. Tout utilisateur voulant utiliser l'état et l'historique des informations dans une preuve SPV sans état peut choisir d'accepter ou de rejeter cette preuve en fonction de sa qualité.

Les preuves SPV sans état sont issues de travaux récents menés par Summa et décrits initialement dans
https://medium.com/summa-technology/cross-chain-auction-technical-f16710bfe69f[un post technique sur le système d'enchères inter-chaîne Summa]. Elles sont pour avantage certain leur faible taille et coût. Une preuve SPV sans état fait moins de 1 KB qui peuvent être supprimés dès la validation effectuée. Un relais garde lui en mémoire chaque en-tête sur la blockchain hôte. Cela veut dire qu'un relais consomme un espace de stockage qui augmente linéairement au cours du temps. Les coûts de maintenance sont déjà bien trop importants comme montré par la défaillance de BTCRelay en décembre 2017. Étant donné le large coût de stockage sur la blockchain hôte et l'introduction probable de "location d'état" dans les blockchain hôtes candidates, compter sur un relai "stateful" semble irréfléchi. Un système "high-state" viable aujourd'hui pourrait ne pas le rester à l'avenir.

Nous pensions que pour des transactions récentes, la sécurité des preuves SPV sans état est équivalente à celle des relais. Un attaquant devrait dépenser la même quantité de hash pour fournir au relai des faux en-tête que s'il voulait fournir au vérificateur SPV une preuve de travail suffisante. En revanche, comparées aux relais, les preuves SPV sans état ne gagnent pas en sécurité au cours du temps sans l'inclusion de nouveaux en-têtes à chaque preuve. Pour que cet argument soit valable, il est important que la régence des transactions soit connue, sans quoi l'attaquant pourrait commencer à générer une preuve en avance, prenant de court la chaîne principale. Les relais ont une garantie de régence à chaque bloc comme chaque en-tête doit référencer l'en-tête qui le précède, mais une preuve SPV sans état doit obtenir la régence d'une source externe. 