:toc: macro

[#bonding]
= Bonding

ifndef::tbtc[toc::[]]

Because signers are able to collude to censor withdrawals or abscond with funds,
a bond is required per deposit from each backing signer.

Unlike the staked work tokens used to choose signers, signer bonds need to be a
liquid asset with a large market cap. This restriction increases the cost of
market-based attacks, where the price of bonded collateral can be pushed up or
down by market manipulation.

Bonded signers offer depositors recourse in the case of colluding signers
interfering with operation. A signing group that doesn't sign within a timeout
forfeits their bond; a signing group that provably signs unauthorized material
forfeits their bond, and risks their work token stake.

== Acceptable collateral

Two tokens present themselves as obvious choices for signing bond collateral--
TBTC and the underlying work token. During the bootstrap phase of the network,
neither is an appropriate candidate due to low liquidity.

Since signer bonds need to be denominated in a widely traded asset to avoid
market manipulation, the next most obvious pick for bonding is the host chain's
native token. For the initial release of tBTC, that means ETH. As the ecosystem
matures, other bond collateral options might become feasible at the expense of a
more complex price feed implementation.

=== Measuring security

:lot-size: 1 BTC

Clearly, security concerns require signing bonds that are proportional to the
size of a _Deposit_. To maintain a negative expected value from signers
colluding, the amount forfeited by misbehaving signers must be strictly greater
than the amount they have to gain. Assuming a lot size of {lot-size}, constant
exchange rate between BTC and the bonded asset, and a
M-of-N group of signers backing a _Deposit_, the minimum collateral for each
signer is `({lot-size})/M`, denominated in the asset being bonded, ETH in the base
case.

Example: Consider a 1 BTC _Deposit_ backed by a 3-of-5 group of Signers. In the
worse case, 3 of the signers can be malicious and try to steal the Deposit,
which would net them each 1/3 BTC. As a result, all 5 Signers must bond 0.33 BTC
each, denominated in ETH.

// In the general case of an m-of-n
// wallet, the minimal set of signers required to collude is _m_, suggesting that
// each signer should bond _ethValue(btcDeposit_/n*(n - m + 1)_.
// note(Georgios): The above n*(n-m+1) did not make much sense to me, you should always use the
// min(m, n), which is always going to be m to calculate your bonding amounts.

=== Pricing currency fluctuations

The above assumes a constant exchange rate between BTC and ETH, but in truth
the two currencies fluctuate relative to each other, sometimes wildly.

==== ETH Price Drop relative to BTC

:extracollateral: 50%
:totalcollateral: 150%

If the value of ETH drops precipitously relative to BTC, then the dollar value
of the ETH bonded by the signers can be less than the dollar value of the BTC
Deposit they have backed, meaning they have positive expected value if they try
to steal the BTC. 

In order to avoid that, we require that the bonds are overcollateralized. For
each ETH they collateralize, they must put up an additional {extracollateral}, for a total of
{totalcollateral} collateralization rate.

**Without overcollateralization:** Let 1 BTC be worth $10000, and 1 ETH be worth $200. Signers have to put up 50 ETH
to back a deposit. Due to market conditions, ETH drops 25% to $150, while
BTC maintains its value. The 50 ETH is worth $7500, meaning the Signers can make
a $2500 profit by stealing the Deposit.

**With overcollateralization:** Let 1 BTC be worth $10,000, and 1 ETH be worth
$200. Signers have to put up 75 ETH (150% of 50) to back a deposit. Due to market conditions,
ETH drops 25% to $150, while
BTC maintains its value. The 75 ETH is worth $11250, which is above the dollar
value of BTC meaning the Signers will maintain honest behavior since they have
more to lose.

In general, total overcollateralization of {totalcollateral} (`3/2 * 100%`) keeps Signer
incentives aligned with the well-being of the system up to a 33% drop (`(1 -
2/3) * 100%`) in price of the bonded asset against the Deposit's asset.
Increasing this percentage can increase the robustness of the system, at
the expense of opportunity cost to the Signers which should be compensated via fees.

If the value of ETH crosses a security threshold, open _Deposit_ s will enter
<<Undercollateralization>>.
 
// TODO insert a little historical analysis for a decent starting number
 
=== BTC Price Drop relative to ETH
 
Since <<Custodial Fees>> are denominated per BTC in custody (with
overcollateralization factored in), a BTC value drop against the
bonded asset translates in lower fees for Signers. Note that this does not
create any issue for tBTC reserves, but it makes the system less attractive to
signers looking to earn interest via fees on their assets.
 
At a certain threshold, a _Deposit_ whose BTC collateral has devalued will move
into a variant of the <<preliq, pre-liquidation>> phase that allows bond
rebalancing without the fallback of signer bond forfeiture.

// TODO insert a little historical analysis for a decent starting number
// Should this actually be called pre-liquidation? In this case, we have a
// Signer overcollateralizing by an amount whihc is more than the minimum, this
// is OK to happen, but is capital inefficient for them. Why not allow them to
// rebalance anytime they want, as long as their collateral is >=150% of btc value?

Example:
Let 1 BTC be worth $10,000, and 1 ETH be worth $200. Signers have to put up 75
ETH to back a deposit. Signers are expected to make a custodial fee of 5 basis
points for $15,000 (150% of $10,000): $7.5. Due to market conditions, ETH soars
25% to $250, while BTC maintains its value. The Signers still get $7.5 per BTC
under custody, however the 75 ETH is worth $18750 (hence 187.5%
overcollateralized), meaning 5 basis points for its custody would be $9.375. The
Signer must be able to reduce their collateral back to 150% to increase their
capital efficiency.

== A resilient price oracle

Unlike popular synthetic stablecoin schemes, the tBTC system design makes no
effort to stabilize the value of TBTC relative to BTC-- TBTC will be priced by
the market. Instead, the goal is to ensure that the TBTC supply is strictly
less than its backing BTC reserves.

For this reason, the only price relationship the system needs to understand is
between the signing bond collateral and BTC. 

In concrete terms, that means the price of ETH to BTC. Due to only needing
prices for a single pair of assets, tBTC will initially use a simple 
<<price-oracle/index.adoc#price-oracle,price oracle>>.

== Undercollateralization

// TODO explain the undercollateralization curve


=== Pre-liquidation: a courtesy call
[[preliq]]

:preliquidation-period: 6 hours
:second-threshold: 125%

At the first threshold, a _Deposit_ enters pre-liquidation. Pre-liquidation
indicates that the signers should be close the _Deposit__ or face forced
liquidation. If the _Deposit_ is not closed within {preliquidation-period}, or
if the _Deposit_ collateral falls below {second-threshold} collateralization,
liquidation will follow. This gives each signer an incentive to close the
position before it becomes severely undercollateralized, as all signers risk
losing funds in the liquidation process.

In future versions of the system, more complex pre-liquidation mechanisms could
be introduced. For the initial version it seems prudent to choose a simple
mechanism with large penalties for ongoing undercollateralization.


=== Liquidation

:auction-start-percent: 80%

Forced liquidation should be rare, as rational signers will redeem _Deposits_
before liquidation becomes necessary. However, the possibility of extreme
punishment via liquidation is necessary to prevent dishonest behavior from
signers. Liquidation may occur because because signers didn't produce a valid
signature  in response a redemption request, because the value of the signing
bond dropped below the collateralization threshold, or because the signers
produced an unauthorized signature.

The primary goal of the liquidation process is to bring the TBTC supply in line
with the BTC custodied by _Deposits_. The most valuable asset held by the
system is the signers' bonds. Therefore, the liquidation process seizes the
signers bonds and attempts to use the bonded value to purchase and burn TBTC.

// TODO: cite uniswap
First, the contract attempts to use on-chain liquidity sources, such as
Uniswap. If the bond is sufficient to cover the outstanding TBTC value on these
markets, it is immediately exchanged for TBTC.

Second, the contract starts a falling-price auction. It offers
{auction-start-percent} of the signer bond for sale for the outstanding TBTC
amount. The amount of bond on sale increases over time until someone chooses
to purchase it, or the auction reaches 100% of the bond. The auction will
remain open until a buyer is found.

TBTC received during this process is burned to maintain the supply peg. If any
bond value is left after liquidation, a small fee is distributed to the account
which trigger liquidation. After that, any remaining value is either
distributed to the signers (in case of liquidation due to
undercollateralization) or burned (in case of liquidation due to fraud).

What the unresponsive signers do with the BTC outside the tBTC system design is
for them to decide-- it might be split up, stolen by a signing majority, or
lost permanently.
