= Bitcoin & friends

P2PKH / P2WPKH:: Pay to (witness) public key hash

P2SH / P2WSH:: Pay to (witness) script hash

Sighash:: Bitcoin signature hash algorithm

BIP 143:: Adopted https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki[SegWit sighash] proposal

ALL:: Sighash mode committing to `ALL` outputs and `ALL` inputs

SINGLE:: Sighash mode committing to `ONE` output and `ALL` inputs

ANYONECANPAY:: Sighash modifier. Changes `ALL` or `SINGLE` to commit to only
`ONE` input

SACP, singleACP:: `SINGLEANYONECANPAY`

Hash160:: Bitcoin hash function `rmd160(sha256(message))`. Used for PKH
commitments in outputs. Used for SH commitments before segwit

Hash256:: Bitcoin hash function `sha256(sha256(message))`. Used for txids,
sighash, merkle trees, and PoW

UTXO:: (unspent) transaction output

Weight unit:: a measure of bitcoin transaction size. Main transaction info is 4
weight units per byte. Witness info is 1 weight unit per byte

Vbyte:: 4 weight units

Outpoint:: A 36-byte string that uniquely identifies Bitcoin UTXOs. It consists
of the creating transaction's `tx_id` as a 32-byte LE `uint256` (because Satoshi
was bad), and a 4-byte LE `uint32` denoting the UTXO's position in the creating
transaction's output vector
