[env.theorem]
:toc: macro

[#price-feed]
= Price Feed

ifndef::tbtc[toc::[]]

The price feed is an integral part of the system, ensuring sufficient collateral backs all tBTC signers. We model the feed after the https://developer.makerdao.com/feeds/[USD price feeds from MakerDAO], operated initially by a single trusted actor and later governed by the ecosystem.

The minimal price feed design is specified completely by the interface below:

[source,solidity]
----
interface PriceFeed {
    function getPrice() external view returns (uint128);
    function updatePrice(uint128 price) public;
}
----

It is principally used for calculating the value of Bitcoin lot deposits, priced in Ether.

== Mechanisms of price feed updates

Price has a built-in expiration of 6 hours. In the unlikely event that the feed is not updated in a timely manner due to miner censorship or other attacks, calls to `getPrice` will revert transactions.

The price feed accepts updates that differ by at least 1% to the previously submitted price.
This mitigates unnecessary recomputations by maintainers for price changes below the threshold. If the price is expiring within 1 hour, this check is ignored.

== Price encoding

A bitcoin has 8 decimal places, the smallest unit being a satoshi, meaning 100 000 000 satoshis = 1 bitcoin.
An ether by contrast, has 18 decimal places, the smallest unit being a wei, meaning
1 000 000 000 000 000 000 wei = 1 ether.

To express the price of bitcoin relative to ether, we must use a ratio of the number of wei to a satoshi.
A simple design is to use `x` wei : 1 satoshi. Hence, for a call to `getPrice` when 32.32 ETH : 1 BTC (Jun 2019),
the value 323 200 000 000 wei is returned.

However, if 1 wei is worth more than 1 sat, then the price can no longer be accurately encoded. This scenario of a 'flippening',
when 1 ether becomes worth 10,000,000,000x as much as 1 bitcoin, we find unlikely in the very short-term.
Rather than prematurely optimize, incorporating a 2 integer ratio of `x` wei to `y` satoshi and changing the call semantics,
we leave this as a future exercise for governance.

== Future design

The price feed is integral to tBTC's security and in the future, will be principally governed by
the tBTC ecosystem. The first upgrades will focus on incorporating a medianizer model from MakerDAO, where
multiple price feeds are voted in and the median price is calculated from their reports. Other on-chain price signals like
decentralized exchanges (DEX's) and liquidity pools (Uniswap) are being considered.
