[#minting]
= Minting

ifndef::tbtc[]
toc::[]

:relfileprefix: ../
:root-prefix: {relfileprefix}
include::../constants.adoc[]
endif::tbtc[]

== Overview

The process of minting TBTC is distinct from the process of depositing Bitcoin.

By splitting minting into two phases—a zero-confirmation deposit creation
yielding a non-fungible token, and an additional proof enabling trade-in of
the non-fungible token for fungible TBTC—we can balance strong security
against reorgs with a better user experience and more flexible use cases.

// TODO insert diagram

== Minting the non-fungible tBTC Deposit Token

After a deposit has been requested and a signing group formed, a depositor
immediately receives a non-fungible token unique to the deposit called the _tBTC
Deposit Token_, or _TDT_, granting them ownership of the deposit. This ownership
comes with the exclusive right to redeem the deposit from the moment it is
funded until the deposit term is reached, unless there is an
undecollateralization issue that transitions the deposit into its "courtesy
call" state.

Once the deposit is fully _qualified_ by submitting sufficient proof of the
funding Bitcoin transaction, the holder of the TDT can request redemption,
and, after paying any outstanding signing fees, the holder is guaranteed the
same UTXO backing the deposit. The holder of the TDT is also guaranteed
compensation in TBTC via the signing group's bonded collateral in case of fraud
or collateralization issues (see
<<bonding/index.adoc#liquidation,liquidation>>), and compensation in TBTC (minus
signer fees) if the deposit is redeemed by another account after it reaches term
(see the section on <<redemption/index.adoc#at-term, at-term redemption>>) or if
the deposit is courtesy called.

=== Implications

There are a few non-obvious implications to a UTXO-specific non-fungible token.

1. Any attacks against the deposit backing a TDT should only impact the token
   holder, rather than the entire supply-pegged currency. Attacks against a
   particular deposit might include Bitcoin reorgs / double spends, DoS
   attacks, malicious signers, or deposit undercollateralization.

2. Any recipient of a TDT will need to evaluate the risk of the token
   themselves. Different tokens might represent different likelihoods of
   reorgs. Deposit owners are free to transfer their TDT, trading it or
   perhaps using it as collateral elsewhere, caveat emptor.

3. TDTs are an ideal target for secret fixed-size "notes" or other financial
   privacy improvements on the host chain.

4. This construction allows delegation of accumulated work SPV proofs to third
   parties. With this functionality, depositors wouldn't necessarily need to
   monitor the Bitcoin blockchain.

// TODO can a deposit be challenged if its proof is re-orged? it appears there's
// no need, but the fungible TBTC vending machine will need to be smart with
// deposits


== Minting fungible TBTC

Once a deposit has accumulated enough work, it is eligible to be traded for
fungible TBTC. The contract managing this is called the "vending machine".

[[vending-machine]]
=== The TBTC vending machine

The TBTC vending machine is a contract on the host chain that is responsible
for minting TBTC.

Any TDT representing a qualified deposit can be exchanged. Qualified deposits
are determined by the accumulated work of their proofs. In tBTC v1, deposits are qualified by a fixed work
requirement proven via an <<appendix/spv/index.adoc#spv,SPV proof>>, set at
{tx-proof-difficulty-factor} of accumulated work.

A TDT representing a qualified deposit is also eligible for minting fungible
TBTC. Minting TBTC is optional; depositors can stick with their TDTs, which
will be valid for the lifetime of a maintained deposit. Note that if a holder
of the TDT wants to make a transaction with a different value than the lot
size, they must mint TBTC, since the tBTC Deposit Token itself is non fungible.

The holder of a qualified TDT may exchange that TDT for a newly minted
{tbtc-lot-size}, less the requisite {signer-fee} signing fee. To reflect the
reduced guarantee of the TDT holder's interest in redeeming the specific
deposit, the signing fee is sent to the deposit to be held in escrow at the
time of TBTC minting.

By exchanging and escrowing, the TDT holder waives their right to exclusive
redemption. As such, they also receive a non-fungible _Fee Rebate Token_, or
_FRT_. This token grants the right to a fee rebate if and when the pre-term
deposit is redeemed by another party. In the rare case that a TDT is used to
mint TBTC, retrieved from the vending machine, and resubmitted to the vending
machine prior to its term expiring, signing fees are only escrowed the first
time a TDT is traded to the vending machine. Since signing fees are not escrowed
the second time the TDT is traded to the vending machine, no FRT is issued at
that time either; instead, the FRT issued the first time the TDT was traded to
the vending machine remains valid.

=== Trading TBTC for tBTC Deposit Tokens

Any TDT held by the vending machine can be obtained for 1 TBTC. The vending
machine MUST burn any TBTC it receives, in any case where it can receive TBTC.

This mechanic has the effect of allowing "unlocked" deposits to be "locked"
in advance for later redemption. In fact, TBTC minting is simply a special case
of locking: a TDT used to mint TBTC is locked to the vending machine, which
provides a straightforward way to transfer it to another account for the cost of
1 TBTC.

Burning all received TBTC allows for maintaining the supply peg not only when
deposit ownership is transferred away from the vending machine, but also when
the deposits that are still owned by the vending machine are liquidated or
<<redemption/index.adoc#at-term, redeemed at term>>, since in these cases
deposit owner compensation goes to the vending machine, which burns that
compensation immediately.
