= tBTC

Deposit:: A deposit is the core component in the system architecture. Each
deposit represents a set of bonded signers that generate a Bitcoin public key
and accept a single Bitcoin UTXO, from which TBTC can be drawn.

Deposit beneficiary:: A deposit has a single beneficiary Ethereum account --
originally set to the depositor. The beneficiary owns the right to some fees
on deposit redemption.

Deposit request:: A request for signers to be selected and generate a new
Bitcoin ECDSA keypair. A successful request yields a new Bitcoin address ready
to accept funds as well as a set of bonded signers.

Lot size:: The ideal size of a funded deposit's BTC UTXO. Standardizing lot
sizes across deposits simplifies the BTC redemption process and pricing of
deposits by the market.

Signing bond:: The bond signers put up before a deposit is funded. This bond
ensures signers will be punished for fraud or poor uptime.

Reserved TBTC:: The amount of TBTC that can't be drawn from a new deposit.
Reserving TBTC on deposit funding sets aside funds to pay signing fee through
the deposit term.
