---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: electrumx
  namespace: default
  labels:
    app: bitcoin
    type: electrumx
spec:
  replicas: 1
  serviceName: electrumx
  volumeClaimTemplates:
  - metadata:
      name: electrumx-data
    spec:
      storageClassName: electrumx
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 30Gi
  selector:
    matchLabels:
      app: bitcoin
      type: electrumx
  template:
    metadata:
      labels:
        app: bitcoin
        type: electrumx
    spec:
      containers:
      - name: electrumx-server
        image: lukechilds/electrumx:v1.16.0
        imagePullPolicy: Always
        ports:
          - name: tcp
            containerPort: 50001
          - name: ssl
            containerPort: 50002
          - name: ws
            containerPort: 50003
          - name: wss
            containerPort: 50004
          - name: rpc
            containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 15
          periodSeconds: 20
        # Full list of env vars: https://electrumx.readthedocs.io/en/latest/environment.html
        env:
          - name: DB_DIRECTORY
            value: /mnt/electrum/data
          - name: SSL_CERTFILE
            value: /mnt/electrum/cert/tls.crt
          - name: SSL_KEYFILE
            value: /mnt/electrum/cert/tls.key
          - name: DAEMON_URL
            valueFrom:
              secretKeyRef:
                name: bcoin
                key: bcoin-url
          - name: SERVICES
            value: tcp://:50001,ssl://:50002,ws://:50003,wss://:50004,rpc://0.0.0.0:8000
          - name: COIN
            value: Bitcoin
          - name: NET
            value: testnet
          - name: COST_SOFT_LIMIT
            value: '0'
          - name: COST_HARD_LIMIT
            value: '0'
          - name: LOG_LEVEL
            value: debug
        volumeMounts:
          - name: electrumx-data
            mountPath: /mnt/electrum/data
          - name: tbtc-network-cloudflare-origin-cert
            mountPath: /mnt/electrum/cert
      volumes:
      - name: electrumx-data
        persistentVolumeClaim:
          claimName: electrumx-data
      - name: tbtc-network-cloudflare-origin-cert
        secret:
          secretName: electrumx-server-test-tbtc-network
