---
apiVersion: v1
kind: Service
metadata:
  name: electrumx
  namespace: default
  labels:
    app: bitcoin
    type: electrumx
spec:
  type: LoadBalancer
  loadBalancerIP: 34.70.22.39
  # Expose the service on ports that are proxied by Cloudflare.
  # See: https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/
  ports:
  - name: tcp
    port: 80
    targetPort: tcp
  - name: ssl
    port: 443
    targetPort: ssl
  - name: ws
    port: 8080
    targetPort: ws
  - name: wss
    port: 8443
    targetPort: wss
  selector:
    app: bitcoin
    type: electrumx
