:toc: macro

= Relay maintainer

== Prerequisites
- https://golang.org/[Go], at least 1.15.7
- https://github.com/ethereum/solidity[Solidity], at least 0.5.17
- https://nodejs.org/en/[Node.js], at least v11.15.0

== Local installation

First, run your Bitcoin and Ethereum nodes. Make sure your Ethereum node
params matches the desired network params in the `solidity/truffle-config.json`
file.

Then, run the install script by doing:
```
./scripts/install.sh
```
You can also run it with the `-h` flag to get more details about its params
and env variables.

After the script finish its work, appropriate relay contract will be deployed
on Ethereum network and the relay client binary will be ready to use.

== Local run

Make sure the desired config file is placed under `config` directory and its
content is right.

Then, invoke the start script by doing:
```
./scripts/start.sh
```
And follow the prompts displayed in the console. After that, the relay client
should be up and running.

== Run in Docker container

Create a config file (let's assume its name is `config.toml`), similar to the
provided `config.toml.SAMPLE`.
Build a docker image and run it using the following commands:
```
docker build -t relay .
docker run -v /path/to/config:/config relay relay -config /config/config.toml start
```

Where `/path/to/config` should be replaced with the path to the directory
containing `config.toml`.


== Metrics

The following metrics are exposed:

* `btc_chain_connectivity`: indicates whether the relay has a working connection
with the BTC chain. Possible values are `1` and `0` which correspond to `true`
and `false` respectively

* `host_chain_connectivity`: does the same as the above metric but is related to
the host chain connectivity

* `headers_relay_active`: indicates whether the header relaying process is
enabled (`1`) or not (`0`)

* `headers_relay_errors`: indicates the total number of errors raised by the
header relaying process during the entire relay node lifetime

* `headers_pulled`: indicates the total number of unique headers pulled from the
BTC chain by the header relaying process, during the entire relay node lifetime.
This metric doesn't count re-pulls which can occur during recovery after header
relaying error

* `headers_pushed`: indicates the total number of unique headers pushed to the
host chain by the header relaying process, during the entire relay node lifetime.
This metric doesn't count re-pushes which can occur during recovery after header
relaying error

By default, the first two `*_chain_connectivity` metrics are updated every
`10 minutes` and this time can be customized via the `Metrics.ChainMetricsTick`
config property. The rest of the metrics are updated every `10 seconds` and
their tick can be set using `Metrics.NodeMetricsTick` property. The metrics
endpoint is `/metrics` and metrics port can be set by the `Metrics.Port`
property. In case it's not set, metrics will not be enabled.


== Reorg support

Relay Maintianer's reorg support was tested and <<./docs/reorgs.adoc#title, documented>>.
