[#custodial-fees]
= Custodial Fees

Signers put their own <<Bonding,funds at risk>> to assure depositors there will
be no foul play. The bonds they put down are capital that could otherwise be
productive, and need to earn a return relative to the risk to remain competitve
with other opportunities.

== Paying for security

There are a number of pricing models that could cover the opportunity cost of
signers' bonds. An adjacent space offers a strongly aligned pricing model.

Today's centralized cryptocurrency custodians charge 50 to 75 basis points
(between 0.5-0.75%) on _assets under custody (AUC)_ per year. For each year
that a centralized custodian protects a bitcoin deposit, that's as much as
0.75% lost to the costs of custody.

A decentralized model should eventually allow a lower effective fee on custody
by introducing more competition to the space. There's a caveat, however-- a
decentralized approach to custodianship makes legal recourse more difficult,
requiring additional bonded collateral to ensure recompense in case of failure.

Applying this pricing model to tBTC's bonding, it's clear that a signer would
like to make a similar return on the total capital it's responsible for-- its
portion of `Deposit` security. In the full threshold case, that's
`1 / min(m, n)` in deposit security, or `1 / m` as `m` is less than `n`, with
`m` signers are required to move funds. Those `m` signers would each require
`1 / m * OverCollateralizationFactor` in  bonds, assuming for a moment a shared
value currency.

For a few conservative values,
`n = 20, m = 15, OverCollateralizationFactor = 150%, LotSize = 1 BTC`, a single
signer can make .0005 TBTC a year per deposit. For depositors, that costs 1.5% a
year. Lowering single-signer returns from 0.75% to 0.25% across the security
value they provide means total signing revenue is 0.5% of the market cap of TBTC
each year, with a return a year of their locked up capital, denominated in TBTC.

While these returns are reasonable relative to their risk in the cryptocurrency
space, we can save both sides money through a more efficient use of capital. As
the network matures, these costs can be lowered through the introduction of
leveraged bonds.
