[#custodial-fees]
= Custodial Fees

Signers put their own <<Bonding,funds at risk>> to assure depositors there will
be no foul play. The bonds they put down are capital that could otherwise be
productive, and need to earn a return relative to the risk to remain competitve
with other opportunities.

== Paying for security

There are a number of pricing models that could cover the opportunity cost of
signers' bonds. An adjacent space offers a strongly aligned pricing model.

Today's centralized cryptocurrency custodians charge 50 to 75 basis points
(between 0.5-0.75%) on _assets under custody (AUC)_ per year. For each year
that a centralized custodian protects a bitcoin deposit, that's as much as
0.75% lost to the costs of custody.

A decentralized model should eventually allow a lower effective fee on custody
by introducing more competition to the space. There's a caveat, however -- a
decentralized approach to custodianship makes legal recourse more difficult,
requiring additional bonded collateral to ensure recompense in case of failure.

Applying this pricing model to tBTC's bonding, it's clear that a Signer would
like to make a similar return on the total capital it is locking up.

## Fee parameterization

### Terminology

- `LotSize`: The exact value of a `Deposit` denominated in `BTC`.
- `OvercollateralizationFactor`: The additional amount which must be deposited as
collateral by the Signer 
- `Deposit`: The amount a `Signer` must lock in a smart contract as
collateral to mint `tBTC`. Initially this will be denominated in `ETH`. `Deposit
= OverCollateralizationFactor * LotSize * (BTCETH conversion rate)`. In the
future, `tBTC` may be used to collateralize a deposit. As a result, assuming a
1:1 ratio between `BTC` and `tBTC`, the price conversion can be skipped.
- `N`: The number of Signers authorized to sign on a `Deposit`'s withdrawal request.
- `M`: The minimum number of Signers required to sign the authoization of a `Deposit`'s withdrawal request.

### Description

It is assumed that each `Signer` contributes equally to the collateralization of
a `Deposit`.

The capital cost per `Signer` is `Deposit / N`. Using `LotSize = 1
BTC` and `OverCollateralizationFactor = 150%`, that is `1.5 BTC / N`.

An initial parameterization of the system will use `15` Signers per lot. In
addition, due to the lack of attributability in the aggregate signature
mechanism used, we pick `M = N`. This inquires a `0.1` BTC value in capital
cost for **each** Signer per `1.0 tBTC` minted.

Taking into account the fees from centralized custodians (`0.00025-0.00075 BTC`),
we choose to reward signers with a flat `0.0005 tBTC` per `1.0 tBTC` minted,
meaning the total signing revenue is `0.5%` of the market cap of the minted amount
of `tBTC` each year.