:toc: macro

[#bonding]
= Bonding

ifndef::tbtc[toc::[]]

Because signers are able to collude to censor withdrawals or abscond with funds,
a bond is required per deposit from each backing signer.

Unlike the staked work tokens used to choose signers, signer bonds need to be a
liquid asset with a large market cap. This restriction increases the cost of
market-based attacks, where the price of bonded collateral can be pushed up or
down by market manipulation.

Bonded signers offer depositors recourse in the case of colluding signers
interfering with operation. A signing group that doesn't sign within a timeout
forfeits their bond; a signing group that provably signs unauthorized material
forfeits their bond, and risks their work token stake.

== Acceptable collateral

Two tokens present themselves as obvious choices for signing bond collateral--
TBTC and the underlying work token. During the bootstrap phase of the network,
neither is an appropriate candidate due to low liquidity.

Since signer bonds need to be denominated in a widely traded asset to avoid
market manipulation, the next most obvious pick for bonding is the host chain's
native token. For the initial release of tBTC, that means ETH. As the ecosystem
matures, other bond collateral options might become feasible at the expense of a
more complex price feed implementation.

=== Measuring security

Clearly, security concerns require signing bonds that are proportional to the
size of a _Deposit_. To maintain a negative expected value from signers
colluding, the amount forfeited by a misbehaving signer must be strictly greater
than the amount they have to gain.

In the case of n-of-n wallets backing each _Deposit_, the minimum collateral
from each signer is _ethValue(bt_Deposit_/n_. In the general case of an m-of-n
wallet, the minimal set of signers required to collude is _m_, suggesting that
each signer should bond _ethValue(bt_Deposit_/n*(n - m + 1)_.

=== Pricing currency fluctuations

The above assumes a constant exchange rate between BTC and ETH, but in truth
the two currencies fluctuate relative to each other, sometimes wildly.

If the value of ETH drops precipitously relative to BTC, a group of malicious
signers will realize that the expected value of theft of the BTC collateral
they protect outweights the cost of loss to their bonds. For this reason, the
value bonded by each signer requires a multiple on the minimum. If the value
of ETH crosses a security threshold, open _Deposit_ s will enter
<<Undercollateralization>>.

// TODO insert a little historical analysis for a decent starting number

If the value of BTC drops precipitously, signers won't make the return on their
bonded capital that they'd hoped-- as <<Custodial Fees>> are denominated in TBTC.
This doesn't pose a problem for tBTC reserves, but is expensive to signers,
lessening their value proposition.

At a certain threshold, a _Deposit_ whose BTC collateral has devalued will move
into a variant of the <<preliq, pre-liquidation>> phase that allows bond
rebalancing without the fallback of signer bond forfeiture.

// TODO insert a little historical analysis for a decent starting number

== A resilient price feed

Unlike popular synthetic stablecoin schemes, the tBTC system design makes no
effort to stabilize the value of TBTC relative to BTC-- TBTC will be priced by
the market. Instead, the goal is to ensure that the TBTC supply is strictly
less than its backing BTC reserves.

For this reason, the only price relationship the system needs to understand is
between the signing bond collateral and BTC.

In concrete terms, that means the price of ETH to BTC. Due to only needing
prices for a single pair of assets, tBTC will initially use a simple price feed
based on MakerDAO's https://developer.makerdao.com/feeds/[Medianizer].

== Undercollateralization

// TODO explain the undercollateralization curve


=== Pre-liquidation: a courtesy call
[[preliq]]

:preliquidation-period: 6 hours
:second-threshold: 125%

At the first threshold, a _Deposit_ enters pre-liquidation. Pre-liquidation
indicates that the signers should be close the _Deposit__ or face forced
liquidation. If the _Deposit_ is not closed within {preliquidation-period}, or
if the _Deposit_ collateral falls below {second-threshold} collateralization,
liquidation will follow. This gives each signer an incentive to close the
position before it becomes severely undercollateralized, as all signers risk
losing funds in the liquidation process.

In future versions of the system, more complex pre-liquidation mechanisms could
be introduced. For the initial version it seems prudent to choose a simple
mechanism with large penalties for ongoing undercollateralization.


=== Liquidation

Forced liquidation should be rare, as rational signers will redeem _Deposits_
before liquidation becomes necessary. However, the possibility of extreme
punishment via liquidation is necessary to prevent dishonest behavior from
signers. Liquidation may occur because because signers didn't produce a valid
signature  in response a redemption request, because the value of the signing
bond dropped below the collateralization threshold, or because the signers
produced an unauthorized signature.

The primary goal of the liquidation process is to bring the TBTC supply in line
with the BTC custodied by _Deposits_. The most valuable asset held by the
system is the signers' bonds. Therefore, the liquidation process seizes the
signers bonds and attempts to use the bonded value to purchase and burn TBTC.

// TODO: cite uniswap
First, the contract attempts to use on-chain liquidity sources, such as
Uniswap. If the bond is sufficient to cover the outstanding TBTC value on these
markets, it is immediately exchanged for TBTC.

Second, the contract starts a falling-price auction. It offers 75% of the signer
bond for sale for the outstanding TBTC amount. The amount of bond on sale
increases over time until someone chooses to purchase it, or the auction
reaches 100% of the bond. The auction will remain open until a buyer is found.

TBTC received during this process is burned to maintain the supply peg. If any
bond value is left after liquidation, a small fee is distributed to the account
which trigger liquidation. After that, any remaining value is either
distributed to the signers (in case of liquidation due to
undercollateralization) or burned (in case of liquidation due to fraud).

What the unresponsive signers do with the BTC outside the tBTC system design is
for them to decide-- it might be split up, stolen by a signing majority, or
lost permanently.
