:toc: macro

= Bonding

ifndef::tbtc[toc::[]]

Because signers are able to collude to censor withdrawals or abscond with funds,
a bond is required per deposit from each backing signer.

Unlike the staked work tokens used to choose signers, signer bonds need to be a
liquid asset with a large market cap. This restriction increases the cost of
market-based attacks, where the price of bonded collateral can be pushed up or
down by market manipulation.

Bonded signers offer depositors recourse in the case of colluding signers
interfering with operation. A signing group that doesn't sign within a timeout
forfeits their bond; a signing group that provably signs unauthorized material
forfeits their bond, and risks their work token stake.

== Acceptable collateral

Two tokens present themselves as obvious choices for signing bond collateral-
TBTC and the underlying work token. During the bootstrap phase of the network,
neither is an appropriate candidate due to low liquidity.

Since signer bonds need to be denominated in a widely traded asset to avoid
market manipulation, the next most obvious pick for bonding is the host chain's
native token. For the initial release of tBTC, that means ETH. As the ecosystem
matures, other bond collateral options might become feasible at the expense of a
more complex price feed implementation.

=== Measuring security

Clearly, security concerns require signing bonds that are proportional to the
size of a `Deposit`. To maintain a negative expected value from signers
colluding, the amount forfeited by a misbehaving signer must be strictly greater
than the amount they have to gain.

In the case of n-of-n wallets backing each `Deposit`, the minimum collateral
from each signer is _ethValue(btcDeposit)/n_. In the general case of an m-of-n
wallet, the minimal set of signers required to collude is _m_, suggesting that
each signer should bond _ethValue(btcDeposit)/n*(n - m + 1)_.

=== Pricing currency fluctuations

The above assumes a constant exchange rate between BTC and ETH, but in truth
the two currencies fluctuate relative to each other, sometimes wildly.

If the value of ETH drops precipitously relative to BTC, a group of malicious
signers will realize that the expected value of theft of the BTC collateral
they protect outweights the cost of loss to their bonds. For this reason, the
value bonded by each signer requires a multiple on the minimum. If the value
of ETH crosses a security threshold, open `Deposit` s will enter
<<Undercollateralization>>.

// TODO insert a little historical analysis for a decent starting number

This threshold will be determined by the contract owner.

If the value of BTC drops precipitously, signers won't make the return on their
bonded capital that they'd hoped- as <<Custodial Fees>> are denominated in TBTC.
This doesn't pose a problem for tBTC reserves, but is expensive to signers,
lessening their value proposition.

At a certain threshold, a `Deposit` whose BTC collateral has devalued will move
into a variant of the <<preliq, pre-liquidation>> phase that allows bond
rebalancing without the fallback of signer bond forfeiture.

This threshold will also be determined by the contract owner.

// TODO insert a little historical analysis for a decent starting number

== A resilient price feed

Unlike popular synthetic stablecoin schemes, the tBTC system design makes no
effort to stabilize the value of TBTC relative to BTC- TBTC will be priced by
the market. Instead, the goal is to ensure that the TBTC supply is strictly
less than its backing BTC reserves.

For this reason, the only price relationship the system needs to understand is
between the signing bond collateral and BTC.

In concrete terms, that means the price of ETH to BTC. Due to only needing
prices for a single pair of assets, tBTC will initially use a simple price feed
based on MakerDAO's https://developer.makerdao.com/feeds/[Medianizer].

== Undercollateralization

// TODO explain the undercollateralization curve
// TODO initially parameters will be set by contract owners

=== Pre-liquidation: the "danger zone"
[[preliq]]

At the first threshold, a `Deposit` enters pre-liquidation.

Pre-liquidations gives live signers an opportunity to rebalance bonds by opening
a new deposit. A new <<Deposit Request,deposit request>> totalling the backing
BTC collateral less custodial and BTC tx fees is issued, and the resulting
payment request is used to construct a withdrawal. On
<<Proof of deposit,proof of deposit>>, the undercollateralized `Deposit` is
closed and the signing bond returned. They're paid out their earned custodial
fees minus the tx fee.

At any time during this process, changes from the price feed can move the
`Deposit` out of pre-liquidation. If no new `Deposit` is funded within a time
window, or the signing collateral continues to devalue, the `Deposit` moves into
liquidation.

// TODO note this violates fixed lot size assumptions as described in
// https://github.com/keep-network/tbtc/issues/3. We can either ask for more
// BTC (ugh), deal with many non-standard deposit sizes, or introduce a
// non-uniform reserve wallet architecture
// https://github.com/keep-network/tbtc/issues/6

=== Liquidation

At some point, either because signers didn't produce a valid signature to move
`Deposit` funds, or because the value of the signing bond continued to quickly
decline, signers' bonded funds will be forfeit.

Forced `Deposit` liquidation favors the `Deposit` owner, first, as they are
losing access to their BTC collateral and the benefit of a guaranteed
withdrawal.

The owner is given a time window to return all withdrawn TBTC. If they do so,
the owner receives *all* signing bond collateral.

If the owner doesn't exercise this option, an auction begins. The purpose of
the auction is to lower the TBTC supply, excluding the now-unprotected BTC
collateral from the reserves.

. Any unwithdrawn TBTC is exchanged pro rata for its portion of the bond.
. The remaining signing bond is put up for auction for TBTC.
. The best TBTC bid larger than a minimum bid of the outstanding TBTC within the
auction's time window wins. If no such bid is made, signers forfeit
progressively more of their backing work token, and the signing bond plus the
additional work token funds seized are put back up for auction.
. All TBTC, including funds unwithdrawn by the `Deposit` owner, custodial fees
earned by signers, as well as the proceeds of the auction, are burned, up to a
ceiling of the TBTC surplus. If any TBTC is left over after, it's given to the
`Deposit` owner.

What the unresponsive signers do with the BTC outside the tBTC system design is
for them to decide- it might be split up, stolen by a signing majority, or lost.
