:toc: macro

= Signing

All of the aforementioned mechanisms require that there is a M-of-N
multisignature wallet guarding each Deposit on Bitcoin. 

Bitcoin's consensus rules restrict script size to 520 bytes (10,000 bytes for Segwit
outputs), limiting the size of multisignature scripts. Future proposals such as
link:https://github.com/bitcoin/bips/blob/master/bip-0114.mediawiki[MAST] would
allow implementing larger multisigs, however the activation of new features on
Bitcoin has historically been a procedure with unclear timelines. 

Finally, large multisignature wallets in Ethereum and Bitcoin both have
increasing verification costs as the number of participants increases. Building
multisgs on Ethereum is link:https://www.coindesk.com/30-million-ether-reported-stolen-parity-wallet-breach[particularly] link:https://www.coindesk.com/ico-funds-among-millions-frozen-parity-wallets[hard]. By
utilizing link:https://crypto.stanford.edu/~dabo/pubs/papers/aggreg.pdf[provably
secure aggregate signatures], we can remove all of the above complexities and
replace them by a simple single signature verification. 

Intuitively, an aggregate public key is generated from all multisignature
participants who communicate via an out of band protocol, a process also known 
as Distributed Key Generation (DKG). Each participant signs the intended message
with their private key and contributes a "share" of the final aggregate
signature. Assuming ECDSA, the aggregate signature can then be verified against the aggregate public key
with an OP_CHECKSIGVERIFY on Bitcoin, or an ECRECOVER operation on Ethereum.
This process is simple and inexpensive, and avoids the path of implementing
complex multisignature verification logic which can be upgraded for different
M-of-N configurations. If another configuration is required, the script or the
smart contract only need to be configured to use a new aggregate public key
after re-executing the DKG.

ifndef::tbtc[toc::[]]

== Threshold ECDSA

== Aborts

== Future Signature Schemes

* Schnorr: MuSig
* BLS